apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:1.27

          ports:
            - containerPort: 80

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: ENVIRONMENT

            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: MESSAGE

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: DB_PASSWORD

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: API_KEY

          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html/data

      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
